name: Terraform Action
description: Setup and Build Terraform Action

inputs:
  tf_api_token:
    description: "HCP API Token"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest
        cli_config_credentials_token: ${{ inputs.tf_api_token }}

    - name: Terraform Init and Validation
      run: |
        terraform init -input=false
        terraform validate
        terraform fmt -check
      shell: bash

    - name: Terraform Plan
      run: |
        terraform plan -no-color -input=false
      shell: bash

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve
      shell: bash
